steps:
  - name: gcr.io/cloud-builders/docker
    args:
      - build
      - -f
      - frontend/Dockerfile
      - -t
      - ${_REGION}-docker.pkg.dev/$PROJECT_ID/cloud-run/sentiment-ui:$COMMIT_SHA
      - --build-arg
      - VITE_API_BASE_URL=${_API_URL}
      - frontend

  - name: gcr.io/cloud-builders/docker
    args:
      - push
      - ${_REGION}-docker.pkg.dev/$PROJECT_ID/cloud-run/sentiment-ui:$COMMIT_SHA

  - name: gcr.io/google.com/cloudsdktool/cloud-sdk
    entrypoint: gcloud
    args:
      - run
      - deploy
      - sentiment-ui
      - --image=${_REGION}-docker.pkg.dev/$PROJECT_ID/cloud-run/sentiment-ui:$COMMIT_SHA
      - --region=${_REGION}
      - --platform=managed
      - --allow-unauthenticated

images:
  - ${_REGION}-docker.pkg.dev/$PROJECT_ID/cloud-run/sentiment-ui:$COMMIT_SHA
